const CORTEX_CONFIG = {
    NEWSDATA_API_KEY: 'YOUR_NEWSDATA_API_KEY',
    CC_API_KEY: 'YOUR_CRYPTOCOMPARE_API_KEY',
    CRYPTOPANIC_TOKEN: 'YOUR_CRYPTOPANIC_AUTH_TOKEN',
    COINGECKO_API_KEY: 'YOUR_COINGECKO_API_KEY',
};

